classDiagram
    class Pessoa {
        <<abstract>>
        - Id: string
        - Nome: string
        - Telefone: string
        - CPF: string?
        - Email: string?
        + Pessoa(id: string?, nome: string, telefone: string, cpf: string?, email: string?)
        + Pessoa(nome: string, telefone: string)
        + Pessoa(nome: string, telefone: string, cpf: string, email: string)
    }

    class Cliente {
        - DtNascimento: DateOnly?
        + Cliente(id: string?, nome: string, telefone: string, cpf: string?, email: string?, dtNascimento: DateOnly?)
        + Cliente(nome: string, telefone: string, cpf: string, email: string, dtNascimento: DateOnly)
        + Cliente(nome: string, telefone: string)
    }

    class Funcionario {
        - Endereco: string
        + Funcionario(id: string?, nome: string, telefone: string, cpf: string, email: string, endereco: string)
        + Funcionario(nome: string, telefone: string, cpf: string, email: string, endereco: string)
    }

    class Servico {
        - Nome: string
        - Descricao: string?
        - Preco: double
        + Servico(nome: string, descricao: string?, preco: double)
        + Servico(nome: string, preco: double)
    }

    class Agendamento {
        - Id: string
        - IdCliente: string
        - IdFuncionario: string
        - DataAgendamento: DateTime
        - DataConclusao: DateTime?
        - IdServicos: string[]
        - Status: string
        - ValorTotal: double
        + Agendamento(id: string, idCliente: string, idFuncionario: string, dataAgendamento: DateTime, dataConclusao: DateTime?, idServicos: string[], status: string, valorTotal: double)
    }

    Pessoa <|-- Cliente
    Pessoa <|-- Funcionario
    Agendamento --> "1" Cliente
    Agendamento --> "1" Funcionario
    Agendamento --> "*" Servico